# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
workflows:
  # Create workflow for testing and deploying PyDynamic.
  test_and_deploy:
    jobs:
      # Create 'test' job to test and install PyDynamic for every commit.
      - test:
          # Include tag filter to trigger as well on tag pushes.
          filters:
              tags:
                only: /.*/
      - deploy:
          # Create 'deploy' job to upload PyDynamic to PyPI.org on certain tag
          #   pushes, which successfully run 'test' job.
          requires:
              - test
          filters:
              tags:
                # Specify the tags which trigger the job as regular expression.
                only: /[0-9]+(\.[0-9]+)*/
              branches:
                # This assures the job only being triggered by tag pushes.
                ignore: /.*/
jobs:
  test:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Checkout code.
      - checkout

      # Create folder for test results.
      - run:
          name: Create test result folder
          command: |
            mkdir test-reports

      # Download and cache dependencies.
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements/requirements.txt" }}
            # Fallback to using the latest cache if no exact match is found.
            - v1-dependencies-

      # Install dependencies and Codecov reporter if necessary.
      - run:
          name: Install dependencies
          command: |
            python3 -m venv test_env
            source test_env/bin/activate
            pip install --upgrade pip
            pip install -r requirements/requirements.txt
            pip install -r requirements/dev-requirements.txt

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements/requirements.txt" }}
          paths:
            - ./test_env

      # Run tests with coverage report and upload results to Codecov!
      - run:
          name: Run tests
          command: |
            source test_env/bin/activate
            pytest -v --junitxml=test-reports/pytest.xml \
            --cov=PyDynamic/ > test-reports/pytest.log

      # Upload coverage report.
      - run:
          name: Upload coverage report
          command: |
            source test_env/bin/activate
            bash <(curl -s https://codecov.io/bash)

      # Install PyDynamic.
      - run:
          name: Install PyDynamic
          command: |
            source test_env/bin/activate
            python3 setup.py install

      # Store test results.
      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_test_results:
          path: test-reports

  deploy:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies.
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "requirements/requirements.txt" }}
            # Fallback to using the latest cache if no exact match is found.
            - v1-dependencies-

      # Install dependencies if needed as well for package creation.
      - run:
          name: Install python dependencies
          command: |
            python3 -m venv build_env
            source build_env/bin/activate
            pip install -r requirements/requirements.txt
            pip install setuptools wheel twine

      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "requirements/requirements.txt" }}
          paths:
            - ./build_env

      # Verify Git tag to version to ensure, only wanted versions are uploaded.
      - run:
          name: Verify Git tag vs. version
          command: |
            source build_env/bin/activate
            python setup.py verify

      # Create a package.
      - run:
          name: Create package
          command: |
            source build_env/bin/activate
            python setup.py sdist bdist_wheel

      # Upload the created packages to test.pypi.org.
      - run:
          name: Upload to PyPI
          command: |
            source build_env/bin/activate
            twine upload dist/*
