# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

executors:
  # Define a parameterized executor which accepts two parameters to choose the python
  # version which will be used for the docker image and the tox actions.
  tester:
    working_directory: ~/repo
    parameters:
      tag:
        type: string
        default: "3.8"
    docker:
      - image: circleci/python:<< parameters.tag >>
  # Define the executor for the Python semantic release.
  publisher:
    working_directory: ~/repo
    parameters:
      tag:
        type: string
        default: "3.8"
      pyenv:
        type: string
        default: "py38"
    docker:
      - image: circleci/python:<< parameters.tag >>
    environment:
      PYENV: << parameters.pyenv >>

commands:
  # Reusable command to prepare the environment for testing.
  create_folders_and_venv:
    description: "Prepare everything."
    parameters:
      pyenv:
        type: string
        default: "py38"
    steps:
    # Checkout code.
    - checkout
    # Create test-result folder.
    - run:
        name: Create test result folder
        command: |
          mkdir test-results

    # Create PyDynamic virtual environment.
    - run:
        name: Create virtual environment
        command: |
          python3 -m venv << parameters.pyenv >>
          source << parameters.pyenv >>/bin/activate
          pip install --upgrade pip setuptools

  # Reusable command to install production dependencies.
  install__production_deps:
    description: "Install production dependencies."
    parameters:
      pyenv:
        type: string
        default: "py38"
    steps:

    # Install dependencies.
    - run:
        name: Install production dependencies
        command: |
          source << parameters.pyenv >>/bin/activate
          pip install -r requirements/requirements-<< parameters.pyenv >>.txt

  # Reusable command to install development dependencies.
  install__development_deps:
    description: "Install development dependencies."
    parameters:
      pyenv:
        type: string
        default: "py38"
    steps:

    # Install dependencies.
    - run:
        name: Install development dependencies
        command: |
          source << parameters.pyenv >>/bin/activate
          pip install -r requirements/dev-requirements-<< parameters.pyenv >>.txt

  # Reusable command to conduct actual testing.
  tox:
    description: "Perform tox testing."
    parameters:
      pyenv:
        type: string
    steps:

    # Perform tox testing.
    - run:
        name: Perform tox testing
        command: |
          source << parameters.pyenv >>/bin/activate
          tox -e << parameters.pyenv >> >> test-results/pytest.log

  # Reusable command to store the previously generated test results.
  store_results:
    description: "Store test results and artifacts."
    parameters:
      pyenv:
        type: string
    steps:
    # Store test results.
    - store_artifacts:
        path: test-results
        destination: test-results

    - store_test_results:
        path: test-results

workflows:
  # Create workflow for testing and deploying PyDynamic.
  test_and_deploy:
    jobs:
      # Create 'test' job to test and install PyDynamic for every commit.
      - test:
          name: "test_python3.5"
          tag: "3.5"
          pyenv: "py35"
      - test:
          name: "test_python3.6"
          tag: "3.6"
          pyenv: "py36"
      - test:
          name: "test_python3.7"
          tag: "3.7"
          pyenv: "py37"
          send_cov: true
      - test:
          name: "test_python3.8"
          tag: "3.8"
          pyenv: "py38"
      - deploy:
          # Create 'deploy' job to create a release and publish it on GitHub,
          # Zenodo and PyPI.org.
          requires:
              - test_python3.5
              - test_python3.6
              - test_python3.7
              - test_python3.8
          filters:
              branches:
                # This assures the job only being triggered on branch master.
                only: /master/
      - test_deploy:
          # Test the 'deploy' job to avoid trouble when Pull Requets get merged.
          requires:
              - test_python3.5
              - test_python3.6
              - test_python3.7
              - test_python3.8
          filters:
              branches:
                # This assures the job is not triggered on branch master, where the
                # `deploy` job itself will be triggered. `test_deploy` is basically
                # `deploy` with the `noop` parameter for `semantic-release` to
                # trigger a dry-run.
                ignore: /master/
jobs:

  # Define one 'test' job with parameters to deal with all desired cases. The
  # reason for this is the desire to ensure the following for all supported Python
  # versions referring to the docs:
  #
  # - all tests are guaranteed to pass
  # - PyDynamic with respect to its `setup.py` successfully installs
  #
  # Additionally we want to create one coverage report during all these tests (which are
  # of course the same for all versions).
  test:
    # Define all parameters, where 'tag' is used for the docker image and 'pyenv' is
    # the string which is used in tox to identify the current Python version. We reuse
    # this variable basically everywhere we deal with the virtual environment.
    # 'send_cov' is the conditional for either sending the produced coverage report
    # to codecov or not.
    parameters:
      tag:
        type: string
        default: "3.8"
      pyenv:
        type: string
        default: "py38"
      send_cov:
        type: boolean
        default: false

    # Specify the executor and hand over the docker image tag parameter.
    executor:
      name: tester
      tag: << parameters.tag >>

    # Specify the steps to execute during this test jobs.
    steps:
      - create_folders_and_venv:
          pyenv: << parameters.pyenv >>
      - install__production_deps:
          pyenv: << parameters.pyenv >>
      - install__development_deps:
          pyenv: << parameters.pyenv >>
      - tox:
          pyenv: << parameters.pyenv >>
      - store_results:
          pyenv: << parameters.pyenv >>

      # Upload coverage report conditionally if the according parameter set to `true`.
      - when:
          condition: << parameters.send_cov >>
          steps:
            - run:
                name: Upload coverage report
                command: |
                  source << parameters.pyenv >>/bin/activate
                  bash <(curl -s https://codecov.io/bash)

  deploy:
    executor:
      name: publisher

    steps:
      - create_folders_and_venv:
          pyenv: ${PYENV}
      - install__production_deps:
          pyenv: ${PYENV}
      - install__development_deps:
          pyenv: ${PYENV}

      # Publish it!
      - run:
          name: Run semantic-release publish
          command: |
            source ${PYENV}/bin/activate
            git config --global user.name "semantic-release (via CircleCI)"
            git config --global user.email "bjoern.ludwig@ptb.de"
            semantic-release publish

  test_deploy:
    executor:
      name: publisher

    steps:
      - create_folders_and_venv:
          pyenv: ${PYENV}
      - install__production_deps:
          pyenv: ${PYENV}
      - install__development_deps:
          pyenv: ${PYENV}

      # Fake publish, just to make sure everything works after merging this PR.
      - run:
          name: Run semantic-release --noop publish
          command: |
            unset CIRCLE_PULL_REQUEST CIRCLE_PULL_REQUESTS CI_PULL_REQUEST \
              CI_PULL_REQUESTS
            export CIRCLE_BRANCH=master
            source ${PYENV}/bin/activate
            git config --global user.name "semantic-release (via CircleCI)"
            git config --global user.email "bjoern.ludwig@ptb.de"
            semantic-release --noop publish
